/* ==========================================
 * TABLE: GAB_4733_TIME
 * ========================================== */
CREATE TABLE "GAB_4733_TIME"(
 "WEEK" CHAR(50) NOT NULL ,
 "DATE" DATE NOT NULL ,
 "DAY" CHAR(10) NOT NULL ,
 "CUSTOMER" CHAR(30),
 "DAYS" DOUBLE,
 "HOURS_VT" DOUBLE,
 "HOURS_RD" DOUBLE,
 "HOURS_SALES" DOUBLE,
 "HOURS_NB" DOUBLE,
 "RATE" DOUBLE,
 "EXTENSION" DOUBLE,
 "NOTES" LONGVARCHAR,
 "ID" INTEGER NOT NULL );


